### ISSUE TITLE
Finished Date changes whilst exporting Excel

### ISSUE THREAD

**Issue by hmtylcnky** [DGH2112/XER-Tools-Public-#2]
Dear David,

Dear David,

First of all, thank you for developing such a useful software and congratulations on its success. I truly appreciate its capabilities.

However, I have encountered an issue when exporting data to Excel or copying and pasting cells into Excel, specifically after changing the activity dates. This problem seems to have surfaced recently as I’m working with 2021 data, and it is the first time I have encountered this error.

To provide more clarity, I’ve included screenshots below:

Excel Version: This shows the issue I’m facing when copying cells:

![Screenshot 2024-12-10 113054](https://github.com/user-attachments/assets/0c9bc999-e9c1-4e10-a980-3bd13e9997a0)

Activities with Actual Start Dates: As far as I understand, the issue might be related to activities that already have an actual start date:

![image](https://github.com/user-attachments/assets/35f539ec-cd83-4663-beeb-50fab3fc8b6a)

Have you encountered a similar issue before? If so, could you suggest any solutions?

Thank you in advance for your assistance.

Best regards,

Thanks in advance

**Comment by hmtylcnky** [comment]
Hi David,

Thank you for your prompt response. I’ve checked, and it works properly. The only minor issue I noticed is that WBS-level durations are not displayed when exporting, but this is not a significant concern.

Additionally, I really appreciate the rendering Gantt chart option—it’s a great feature!

Thanks again for your support. I’ll keep this between us until you share it publicly on your page.

Best Regards,
Ahmet

**Comment by DGH2112** [comment]
Ahmet,
I'll look into the WBS durations.
regards
David Hoyle
https://github.com/DGH2112

**Comment by hmtylcnky** [comment]
Hi David,

Beta version expired. If possible, can you share new version?

Thanks in advance.

Best Regards,
Ahmet

**Comment by DGH2112** [comment]
Ahmet,
This will be the last Beta before the new release.
[XERTools64.zip](https://github.com/user-attachments/files/19164175/XERTools64.zip)
regards
Dave.

**Comment by hmtylcnky** [comment]
Thanks David,

Regards,
Ahmet
